name: Security Scan on Deploy

on:
  push:
    branches:
      - master

jobs:
  snyk_scan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Snyk CLI
        run: |
          apt-get install npm
          npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test for vulnerabilities
        run: snyk test --all-projects > snyk_scan.txt
        continue-on-error: true

      - name: Uploading results
        uses: actions/upload-artifact@v3
        with:
          name: snyk_scan_output
          path: snyk_scan.txt
